name: Check Merge Conflicts

on: pull_request

jobs:
  check_conflicts:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: mschilde/auto-label-merge-conflicts@master
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 5
          WAIT_MS: 5000